/*
============================================================
AlphaLens - Automated Event Brief Lifecycle
============================================================

Purpose:
    Link watched-company alerts to automatically generated event briefs and
    preserve retry and quality-gate state for unattended ingestion runs.

Behavior:
    A failed generation remains retryable, while a passed or rejected brief
    keeps the exact evaluation that produced its terminal state. Saved briefs
    record whether they were requested manually or generated by automation.
============================================================
*/


ALTER TABLE event_briefs
ADD COLUMN IF NOT EXISTS accession_number TEXT;


ALTER TABLE event_briefs
ADD COLUMN IF NOT EXISTS transcript_id BIGINT;


ALTER TABLE event_briefs
ADD COLUMN IF NOT EXISTS generation_source VARCHAR(20) NOT NULL DEFAULT 'manual';


ALTER TABLE event_briefs
DROP CONSTRAINT IF EXISTS event_briefs_generation_source_check;


ALTER TABLE event_briefs
ADD CONSTRAINT event_briefs_generation_source_check
CHECK (generation_source IN ('manual', 'automatic'));


ALTER TABLE event_briefs
ADD COLUMN IF NOT EXISTS quality_evaluation JSONB NOT NULL DEFAULT '{}'::JSONB;


ALTER TABLE event_alerts
ADD COLUMN IF NOT EXISTS brief_id BIGINT
    REFERENCES event_briefs(brief_id)
    ON DELETE SET NULL;


ALTER TABLE event_alerts
ADD COLUMN IF NOT EXISTS brief_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';


ALTER TABLE event_alerts
DROP CONSTRAINT IF EXISTS event_alerts_brief_status_check;


ALTER TABLE event_alerts
ADD CONSTRAINT event_alerts_brief_status_check
CHECK (brief_status IN ('PENDING', 'GENERATING', 'PASSED', 'REJECTED', 'FAILED'));


ALTER TABLE event_alerts
ADD COLUMN IF NOT EXISTS brief_attempt_count INTEGER NOT NULL DEFAULT 0;


ALTER TABLE event_alerts
ADD COLUMN IF NOT EXISTS brief_error TEXT;


ALTER TABLE event_alerts
ADD COLUMN IF NOT EXISTS brief_evaluation JSONB NOT NULL DEFAULT '{}'::JSONB;


ALTER TABLE event_alerts
ADD COLUMN IF NOT EXISTS brief_last_attempt_at TIMESTAMPTZ;


ALTER TABLE event_alerts
ADD COLUMN IF NOT EXISTS brief_generated_at TIMESTAMPTZ;


CREATE INDEX IF NOT EXISTS idx_event_alerts_brief_queue
ON event_alerts (brief_status, brief_attempt_count, created_at);


CREATE INDEX IF NOT EXISTS idx_event_briefs_generation_source
ON event_briefs (generation_source, created_at DESC);
